def get_performance_encoding():
    performance_encoding = {}
    for i in range(100):
        performance_encoding["(" + str(i) + ", ON)"] = str(i)
        performance_encoding["(" + str(i) + ", OFF)"] = str(i + 100)
        performance_encoding["(" + str(i) + ", SHIFT)"] = str(i + 200)
    return performance_encoding


PERFORMANCE_ENCODING = get_performance_encoding()


XML_KEYWORDS = [
    "score-partwise",
    "version",
    "work",
    "work-title",
    "stem",
    "note",
    "text",
    "type",
    "duration",
    "line",
    "default-x",
    "default-y",
    "pitch",
    "step",
    "lyric",
    "syllabic",
    "encoding",
    "software",
    "encoding-date",
    "identification",
    "creator",
    "width",
    "number",
    "measure",
    "end",
    "part-name",
    "mode",
    "time",
    "fermata",
    "fifths",
    "attributes",
    "notations",
    "alter",
    "beats",
    "part",
    "width",
    "quarter",
    "half",
    "part-list",
    "score-part",
    "eighth",
    "whole",
    "down",
    "up",
    "sign",
    "clef",
    "beat-type",
    "scaling",
    "defaults",
    "octave",
    "common",
    "continue",
    "stop",
    "tied",
    "accidental",
    "double-sharp",
    "sharp",
    "flat",
    "32nd",
    "16th",
    "beam",
    "midi-channel",
    "midi-program",
    "begin",
    "instrument-name",
    "double-flat",
    "64th",
    "id",
    "midi-instrument",
    "score-instrument",
    "repeat",
    "direction",
    "chord",
    "modification",
    "dynamics",
    "score",
    "single",
    "margin",
    "movement",
    "left",
    "right",
    "millimeters",
    "millimeter",
    "divisions",
    "music",
    "abbreviation",
    "composer",
    "version",
    "print",
    "piano",
    "Soprano",
    "MuseScore",
    "distance",
    "major",
    "minor",
    "style",
    "finale",
    "Instrument",
    "light",
    "heavy",
    "Macintosh",
    "page",
    "natural",
    "slur",
    "backward",
    "part-abbreviation",
    "forward",
    "placement",
    "normal",
    "above",
    "below",
    "ornaments",
    "display",
    "Music21",
    "start",
    "tenths",
    "movement-title",
    "tie",
    "new-system",
    "system-layout",
    "system-distance",
    "name",
    "location",
    "direction-type",
    "symbol",
    "key",
]

KEYWORDS = sorted(XML_KEYWORDS, key=len, reverse=True)
